import logging

logging.warning("Prova di errore")
